### ISSUE TITLE
Replace english content with slovakian in package/README file

### ISSUE THREAD

**Issue by kr8n3r** [slovensko-digital/navody-frontend#105]
https://github.com/slovensko-digital/navody-frontend/blob/master/package/README.md still contains content from the forked govuk-frontend project. 

As this folder is packaged for NPM, the content appears on https://www.npmjs.com/package/navody-digital-frontend

You might want to change that, so that your users don't get confused.

**Comment by eronisko** [comment]
@kr8n3r Thanks for the heads-up! I've updated the README file to link to our repo/github/etc.
