### ISSUE TITLE
Search na mobile je velky

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody-frontend#115]
![image](https://user-images.githubusercontent.com/26342/70419410-a88c2f80-1a65-11ea-8501-d81e4a558f49.png)

Toto by sme mali nejako na mobile vyriesit.

**Comment by tajovic** [comment]
Seach input navrhujem na malej obrazovke dat full width (v ramci gridu) a Hľadať tlacidlo dat pod to tiez vo full width. Jednotlive karty by som na malych obrazovkach taktiez natiahol na full width aby boli pod seba a nie vedla seba.

**Comment by rakyi** [comment]
Ja by som to navrhol spravit ako gov.uk. "Hľadať" zmeniť za ikonu lupy na malej obrazovke.

![image](https://user-images.githubusercontent.com/6129025/74085804-38a61f80-4a7d-11ea-904f-f8cd6ce450b8.png)

**Comment by rakyi** [comment]
Moja chyba, toto sa malo zavrieť, až keď sa na [navody.digital](https://github.com/slovensko-digital/navody.digital) použije nová verzia balíka, ktorá bude obsahovať #122. Čiže to ešte môžte otvoriť, kto máte práva a chuť, lebo to zatiaľ nemáme nasadené.
