### ISSUE TITLE
Header: dorobit dropdown menu + ikonku a meno pouzivatela

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody-frontend#15]
http://navody-frontend.staging.slovensko.digital/custom-components/header

+ modalne okno s formularom na prihlasenie (email) s vysvetlenim, ze dojde magic link & FB login tlacidlo

**Comment by himak** [comment]
urobim to, je na to dizajn ?

**Comment by filiplikavcan** [comment]
Toto je riesene na samostatnej stranke. Na teraz je to podla mna dobre riesenie.
