### ISSUE TITLE
Timeline: Dorobit zobrazovanie dropdownu a integraciu s backendom

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody-frontend#16]
http://navody-frontend.staging.slovensko.digital/custom-components/timeline

Must have:
- zobrazovanie cez js
- skryvanie ineho otvoreneho dropdownu
- optimisticka zmena stavu (hned po zvoleni sa vizualne zmeni stav)
- integracia s backendom (na dalsiu diskusiu ako to integrovat: napr. cez konvencie (napr. url endpointu v data atribute), alebo spravit onchange event, ktory si integrator odchyti ako potrebuje)

Do buducnosti:
- pouzitelnost bez javascriptu (iframe?, samostatna url s formularom na zmenu stavu kroku, cely timeline ako formular a jednotlive kroky ako selecty so stavmi? - na diskusiu)

**Comment by jsuchal** [comment]
![image](https://user-images.githubusercontent.com/26342/49718869-a7120680-fc5b-11e8-8c11-dfde0f60f6e0.png)

Ta fajka vyzera byt trochu divna. Ma to byt biele a takto nezarovnane?

**Comment by filiplikavcan** [comment]
@jsuchal Ikonka je uz opravena v #37
