### ISSUE TITLE
Todolist: Dorobit integraciu s backendom

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody-frontend#17]
http://navody-frontend.staging.slovensko.digital/custom-components/todo-list

Sposoby integracie na diskusiu, niektore moznosti:

- on change event checkboxu a zmenu si poriesi integrator
- konvencia (napr. data atribut s url, na ktoru sa ajaxom posle request so zmenenym stavom checkboxu)

Pouzitelnost bez javascriptu, na diskusiu:

- tlacidla namiesto checkboxov, ktore submitnu formular
- checkboxy obalene vo forme a jedno tlacidlo, ktorym sa submitne stav checkboxov

**Comment by jsuchal** [comment]
Este mozeme spravit to, ze proste bude kazdy checkbox jeden mikroform a submitne sa to onclick. Backend testovanie to vie nasimulovat.

**Comment by filiplikavcan** [comment]
A on change event by vam nestacil? To mi pride ako najcistejsie riesenie. A integrator nech si poriesi na ten onchage co chce, napr. submit formulara alebo ajax request a nech si v testoch namockuje toto ako potrebuje.

**Comment by jsuchal** [comment]
@filiplikavcan podla mna na strane templatov predsa nejaky JS ani riesit netreba nie? Len ide o tom, aby sa to nerozbilo ked tam dame form.

**Comment by filiplikavcan** [comment]
To je dobra otazka, ze co je vlastne tento todo list a ako uzko to bude integrovane s centralou. Ak to bude len komponent pre vyvojarov appiek, tak fakt staci len obalit to do formu a nechat to na vyvojarov ako to naimplementuju a otestuju.

**Comment by jsuchal** [comment]
Toto bude len na centrale si myslim.

**Comment by jsuchal** [comment]
Urcite treba lebo standardne tam budu veci co si potrebujes sam odskrtnut. Napr. "mam vybavene toto potvrdenie" co sa automaticky neda
