### ISSUE TITLE
Feedbackbar: Dorobit formular na odoslanie feedbacku

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody-frontend#18]
http://navody-frontend.staging.slovensko.digital/custom-components/feedbackbar

Chceme funkcnost feedback baru z gov.uk stranok (napr. tu https://www.gov.uk/), ktory je nad footrom.

Default stav (toto uz mame):
<img width="1001" alt="screenshot 2018-12-08 at 13 02 20" src="https://user-images.githubusercontent.com/1244233/49685749-9f325500-fae9-11e8-8987-156702ffdd9b.png">

Stav po kliknuti na ANO:
<img width="1004" alt="screenshot 2018-12-08 at 13 02 26" src="https://user-images.githubusercontent.com/1244233/49685750-9f325500-fae9-11e8-805e-fafbf9208ff8.png">

Stav po kliknuti: Nasli ste chybu
<img width="1019" alt="screenshot 2018-12-08 at 13 02 37" src="https://user-images.githubusercontent.com/1244233/49685751-9fcaeb80-fae9-11e8-8fc9-325d24011887.png">

Stav po kliknuti na nie
<img width="1012" alt="screenshot 2018-12-08 at 13 02 47" src="https://user-images.githubusercontent.com/1244233/49685752-9fcaeb80-fae9-11e8-80dc-42b5ef4e1ef3.png">

**Comment by mascot4m** [comment]
Toto je uz asi done, nie?

**Comment by jsuchal** [comment]
Ano. Mozeme zavriet.

**Comment by eronisko** [comment]
Áno
