### ISSUE TITLE
Drobnosti s headerom

### ISSUE THREAD

**Issue by eronisko** [slovensko-digital/navody-frontend#42]
V headeri som narazil na zopar potencialnych much, mozete sa na to prosim pozriet?

- [ ] Zvlastny border
Na bielom pozadi to dobre nevidno, ale uplne nalavo ma header svetlomodry border. A vyzera to, ze ma border okolo obrysu, to neviem ci je by design ale necakal som to.
![image](https://user-images.githubusercontent.com/1374745/50959263-d6b66780-14c2-11e9-88d9-71fbd807d893.png)

- [ ] Dropdown sa neotvara ako by som cakal
Ak sa cez https://staging.navody.digital/ prihlasim (zadajte tam hocico), dropdown sa vyroluje onmousedown namiesto nejakeho hoveru alebo tak.

- [ ] Dropdown je prekryty
Dropdown je prekryty buttonom:
![image](https://user-images.githubusercontent.com/1374745/50959685-cd79ca80-14c3-11e9-910c-efe87720df14.png)

**Comment by eronisko** [comment]
Taktiez na dropdowne sa mi nedari klikat. Toto by bolo dobre fixnut co najskor, kedze sa kvoli tomu teraz neda odhlasit :)

**Comment by filiplikavcan** [comment]
Dropdown nechame zatial na click. Aj bootstrap to tak ma.
