### ISSUE TITLE
Suhlas s cookies 

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody-frontend#56]
doplnit dole nutnost acceptnut cookies okno

**Comment by mascot4m** [comment]
Toto vyzera, ze uz je hotove, ci este nieco tam treba?

![image](https://user-images.githubusercontent.com/7282140/56969601-c86d8380-6b65-11e9-8ead-bd47e6d2a3fe.png)

**Comment by HanaBene** [comment]
done, zatvaram
