### ISSUE TITLE
Responzivita

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody-frontend#69]
- [x] prva polozka v menu je orezana
- [x] doladit menu -> definovat media query css pre appku
- [x] zoznam uloh na mobile je pod navodom + nadpis
- [x] paddingy/marginy
- [x] feedbackbar presahuje cez okno
- [x] dorobit sipku do Dalsi krok
- [x] responzivita dvoch buttonov
- [x] "cudne" vyzerajuci pasik s beta verziou
- [x] pohrat sa s footrom
- [x] zacat cely navod odznovu je nad navodom, treba to lepsie umiestnit aby to nebol focus point
- [x] informacne stranky (autori, ako sa zapojit) nemaju margin
- [x] ako sa zapojit ma buttony pod sebou, treba doriesit layout (desktop to ma na tretiny)
- [ ] zobrazit nadpis nad zoznamom uloh na mobile

**Comment by jsuchal** [comment]
@HanaBene ak mozes preklikaj to na mobile a dopln veci, pripadne hocikto z komunity.

**Comment by HanaBene** [comment]
- zacat cely navod odznovu je nad navodom, treba to lepsie umiestnit aby to nebol focus point
- informacne stranky (autori, ako sa zapojit) nemaju margin
- ako sa zapojit ma buttony pod sebou, treba doriesit layout (desktop to ma na tretiny)

**Comment by filiplikavcan** [comment]
K "zacat cely navod odznovu". To planujeme cele prehodit na koniec. Takto:
![screencapture-staging-navody-digital-moje-zivotne-situacie-63-krok-informovat-zamestnavatela-2019-04-03-13_19_44](https://user-images.githubusercontent.com/1244233/55475066-31b7b080-5613-11e9-86ce-8badbe873726.png)

**Comment by HanaBene** [comment]
![hladat](https://user-images.githubusercontent.com/45393631/55478404-f53c8280-561b-11e9-8bf4-a7c1f36df1e0.PNG)
hladat okno je odrezane z pravej strany

**Comment by likavan** [comment]
> * informacne stranky (autori, ako sa zapojit) nemaju margin

v template treba cely obsah obalit este do div.govuk-grid-column-full aby sa vyrovnal zaporny margin .govuk-grid-row

**Comment by jsuchal** [comment]
@HanaBene @filiplikavcan mozeme zavriet nie?
