### ISSUE TITLE
UX: Zjednotit navody a aplikacie na titulke

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody-frontend#82]
Pri volbach sme mali ten problem, ze aplikacia na ziadost o hlasovaci preukaz bola schovana v navode a ludia ju nevedeli najst. Mozno by sme mali na titulke nerozlisovat medzi navodmi a apkami ale mat moznost tam dat odkaz na hocico (trebars aj skupinu navodov vid https://github.com/slovensko-digital/navody.digital/issues/148). Treba domysliet UX tohto (budeme ich odlisovat nejakym tagom?) a ako sa bude spravat potom napriklad aj vyhladavanie. 

Nemam na toto silny nazor, ale nieco taketo by sa hodilo ked budeme mat viac aplikaci/sluzieb tak vlastne nie je nikde zoznam kde na ne vieme odkazat (zatial len z navodu), pritom aplikacie mozu byt uplne "samonosne" ako napr. hlasovaci preukaz.

**Comment by tajovic** [comment]
Ja by som odporucil medzi tym nejak velmi nerozlysovat. Pouzivatel pride na portal vyriesit svoj problem. Ci je to pomocou navodu, ktory si musi precitat alebo pomocou appky, ktoru musi vyplnit, vsetko je to v jednotnom dizajne a ma to jednotny ciel – vyriesit pouzivatelov problem. Na homepage by som teda odporucil umoznit pridavanie ako navodov, tak aj samostatnych appiek, pripadne skupine navodov.
Na zlepsenie ocakavania pre viac tech savvy pouzivatelov je mozne na kartu navodu/appky umiestnit maly tag, ktory pouzivatela informuje o tom ci bude v buducich par minutach vela citat alebo vela vyplnat. Nedaval by som tam zrejme uplne slova Navod alebo Aplikacia. Mozno Navod a Formular alebo nieco take. Interne to pre vas je appka, ale pre pouzivatela ani moc nie. Pre menej tech savvy pouzivatelov by tento tag nemal byt moc rusivy.
Samozrejme, ze zbieranie feedbacku a iterovanie je nutne a moze sa ukazat, ze toto odporucanie nie je optimalne vzhladom na pouzivatelnost.

**Comment by jsuchal** [comment]
Toto uz je hotove, zatial nerozlisujeme.
